---
title: "Material"
subtitle: "Material da disciplina introR: introdução à linguagem R."
page-layout: full
title-block-banner: false
toc: true
editor: source
---

| Dia   | Atividade                                                                 | Slides |
|-------|----------------------------------------------------------------------------|:------:|
| Dia 01| Boas-vindas e apresentações                                                | `r icons::icon_link("file-slides", href = "#")` |
| Dia 01| Aula teórica 1: ciência aberta e controle de versão                        | `r icons::icon_link("file-slides", href = "#")` |
| Dia 01| Aula prática 1: prática com git e repositórios no GitHub                   | `r icons::icon_link("file-slides", href = "#")` |
| Dia 02| Aula teórica 2: introdução à programação em R (Base R)                     | `r icons::icon_link("file-slides", href = "#")` |
| Dia 02| Aula teórica 3: introdução à programação em R (tidyverse)                  | `r icons::icon_link("file-slides", href = "#")` |
| Dia 03| Aula teórica 4: tópicos avançados em programação no R (controle de fluxo, repetições e funções) | `r icons::icon_link("file-slides", href = "#")` |
| Dia 03| Aula prática 2: integração entre R e git/GitHub em trabalho científicos    | `r icons::icon_link("file-slides", href = "#")` |
| Dia 04| Projeto prático: desenvolvimento de uma análise ecológica reprodutível usando R e git/GitHub (em grupos) | `r icons::icon_link("file-slides", href = "#")` |
| Dia 04| Projeto prático: apresentação dos projetos práticos                        | `r icons::icon_link("file-slides", href = "#")` |
| Dia 04| Discussão: reprodutibilidade e transparência em ciência, desafios e perspectivas no uso de R e git/GitHub para ecologia | `r icons::icon_link("file-slides", href = "#")` |
| Dia 04| Encerramento da disciplina                                                 | `r icons::icon_link("file-slides", href = "#")` |


<style>
#topBtn {
  display: none;
  position: fixed;
  bottom: 105px; /* um pouco acima do fundo */
  left: 50%;
  transform: translateX(-50%);
  padding: 10px 14px;
  font-size: 20px;
  border: none;
  border-radius: 6px;
  background-color: #2381df; 
  color: white;
  cursor: pointer;
  box-shadow: 0 2px 6px rgba(0,0,0,0.3);
  transition: background-color 0.3s;
}
#topBtn:hover {
  background-color: rgba(0, 86, 179, 0.9);
}
</style>

<button id="topBtn" onclick="window.scrollTo({top: 0, behavior: 'smooth'});">↑ Topo</button>

<script>
const btn = document.getElementById("topBtn");

window.addEventListener("scroll", () => {
  const scrollBottom = window.innerHeight + window.scrollY;
  const docHeight = document.documentElement.scrollHeight;

  if (scrollBottom >= docHeight - 200) { // aparece um pouco antes do final
    btn.style.display = "block";
  } else {
    btn.style.display = "none";
  }
});
</script>
