---
title: "Tarefas"
subtitle: "Tarefas da disciplina introR: introdução à linguagem R."
page-layout: full
title-block-banner: false
toc: true
editor: source
---

## Aula prática 1: controle de versão

- Leitura extra: [GitHub para desentendidos](https://www.fernandakellyrs.com/post/github-para-desentendidos).

- Leitura extra: [Como usar o Git e Github na prática](https://github.com/rafaballerini/GitTutorial).

- Leitura extra: [Utilizando o Git e GitHub no RStudio](https://beatrizmilz.github.io/slidesR/git_rstudio).

- Exercícios extras: [git - guia prático](https://rogerdudler.github.io/git-guide/index.pt_BR.html).

- Exercícios extras: [Learn Git Branching](https://learngitbranching.js.org).

- Exercícios extras: [Learn & practice Git](https://gitexercises.fracz.com/).

## Aula teórica 2: introdução à programação em R (Base R)

- Leitura extra: [Capítulo 4 - Análises Ecológicas no R](https://analises-ecologicas.com/cap4).

- Leitura extra: [Introdução ao R - Bookdown](https://bookdown.org/wevsena/curso_r_tce/curso_r_tce.html).

- Leitura extra: [Introdução ao R - Bookdown](https://bookdown.org/wevsena/curso_r_tce/curso_r_tce.html).

- Leitura extra: [Introdução ao uso do programa R - Victor Lemes Landeiro](https://cran.r-project.org/doc/contrib/Landeiro-Introducao.pdf).

- Exercícios extras: [capítulo 4 - Análises Ecológicas no R](https://analises-ecologicas.com/cap4#exerc%C3%ADcios).

- Exercícios extras: [R para Ciência de Dados I](https://curso-r.github.io/202209-r4ds-1/).

- Exercícios extras: [Lista de Exercícios - RPubs](https://rpubs.com/adlauro/896610).

- Exercícios extras: [Introdução ao R](https://gent-esalq.github.io/cursoR/cursoR_pdf.pdf).

## Aula teórica 3: introdução à programação em R (tidyverse)

- Leitura extra: [Capítulo 5  - Análises Ecológicas no R](https://analises-ecologicas.com/cap5).

- Leitura extra: [Aprenda a utilizar o tidyverse](https://laddem.github.io/courses/tidyverse/).

- Leitura extra: [Introdução à Análise de Dados em R utilizando Tidyverse](https://allanvc.github.io/book_IADR-T/m2.html).

- Exercícios extras: [capítulo 5 - Análises Ecológicas no R](https://analises-ecologicas.com/cap5#exerc%C3%ADcios).

- Exercícios extras: [Introdução ao Tidyverse](https://www.datacamp.com/pt/courses/introduction-to-the-tidyverse).

- Exercícios extras: [Fundamentos do Tidyverse em R](https://www.datacamp.com/pt/tracks/tidyverse-fundamentals).

## Aula teórica 4: introdução à programação em R (visualização)

- Leitura extra: [Capítulo 6  - Análises Ecológicas no R](https://analises-ecologicas.com/cap6).

- Leitura extra: [The R Graph Gallery](https://r-graph-gallery.com/).

- Leitura extra: [R Charts](https://r-charts.com/).

- Exercícios extras: [capítulo 6 - Análises Ecológicas no R](https://analises-ecologicas.com/cap6#exerc%C3%ADcios).

- Exercícios extras: [Data Visualization in R with ggplot2](https://sscc.wisc.edu/sscc/pubs/dvr/exercises.html).

## Aula teórica 5: tópicos avançados em programação no R

- Leitura extra: [Capítulo 3 - Ciência de Dados em R](https://livro.curso-r.com/3-12-controle-de-fluxo.html).

- Leitura extra: [Fluxo de Controle e Laços](https://www.datanovia.com/learn/programming/r/basics/control-flow-and-loops.html).

- Leitura extra: [Capítulo 5 - Advanced R](https://adv-r.hadley.nz/control-flow.html).

- Leitura extra: [Capítulo 9 - Advanced R](https://adv-r.hadley.nz/functionals.html).

- Leitura extra: [Estruturas de Controle de Fluxo](https://docentes.univasf.edu.br/marcelo.linder/arquivos_ap/aulas_M2/aula6.pdf).

- Exercícios extras: [Controle de Fluxo e Laços](https://sachsmc.github.io/r-programming/exercises/flow-and-loops.html).

- Exercícios extras: [Controle de Fluxo](https://docs.ycrc.yale.edu/r-novice-gapminder/07-control-flow/).

- Exercícios extras: [Laços Avançados](https://www.dataquest.io/course/intermediate-r/).

- Exercícios extras: [Estruturas de Repetição](https://pt.scribd.com/document/735723153/Exercicios-para-estudar-programacao-Lista-3).

## Aula prática 6: reprodutibilidade em R e GitHub

- Leitura extra: [Capítulo 28 - R para Ciência de Dados](https://pt.r4ds.hadley.nz/quarto.html?utm_source=chatgpt.com).

- Leitura extra: [Estatística computacional](https://prdm0.github.io/aulas_computacional/index.html).

- Leitura extra: [Relatórios reprodutíveis com R](https://beatrizmilz.github.io/2024-curso-de-verao-ime-usp-relatorios/).

- Leitura extra: [Reproducible R](https://rockefelleruniversity.github.io/RU_reproducibleR/).

- Leitura extra: [Reproducible Research in R](https://r-cubed-intro.rostools.org/).

- Leitura extra: [Building Skills in Quantitative Biology](https://www.quantitative-biology.ca/r-markdown.html).

<style>
#topBtn {
  display: none;
  position: fixed;
  bottom: 105px; /* um pouco acima do fundo */
  left: 50%;
  transform: translateX(-50%);
  padding: 10px 14px;
  font-size: 20px;
  border: none;
  border-radius: 6px;
  background-color: #2381df; 
  color: white;
  cursor: pointer;
  box-shadow: 0 2px 6px rgba(0,0,0,0.3);
  transition: background-color 0.3s;
}
#topBtn:hover {
  background-color: rgba(0, 86, 179, 0.9);
}
</style>

<button id="topBtn" onclick="window.scrollTo({top: 0, behavior: 'smooth'});">↑ Topo</button>

<script>
const btn = document.getElementById("topBtn");

window.addEventListener("scroll", () => {
  const scrollBottom = window.innerHeight + window.scrollY;
  const docHeight = document.documentElement.scrollHeight;

  if (scrollBottom >= docHeight - 200) { // aparece um pouco antes do final
    btn.style.display = "block";
  } else {
    btn.style.display = "none";
  }
});
</script>
