project:
  type: website
  output-dir: docs

lang: pt-BR

website:
  title: "introR"
  favicon: img/favicon.ico
  navbar:
    logo: img/favicon.ico
    tools:
    - icon: github
      href: https://github.com/course-intror
      target: _blank
    - icon: chat-fill
      href: https://github.com/orgs/course-intror/discussions
      target: _blank
    right:
      - text: Plano de ensino
        aria-label: "Plano de ensino"
        href: syllabus/index.qmd
      - text: Cronograma
        aria-label: "Cronograma"
        href: schedule/index.qmd  
      - text: Leituras
        aria-label: "Leituras"
        href: reading/index.qmd
      - text: Tarefas
        aria-label: "Tarefas"
        href: task/index.qmd
      - text: Projetos
        aria-label: "Projetos"
        href: project/index.qmd

  page-footer:  
    left: >-
     &#169; 2025 Maurício Vancine &#8729; Feito com [Quarto](https://quarto.org){target="_blank"}.
    right: 
      - text: "Contato"
        aria-label: "Contato"
        href: contact.qmd
      - text: "Licença"
        aria-label: "License Details"
        href: license.qmd
      - text: "Financiamento"
        aria-label: "Financiamento"
        href: contributors.qmd

format:
  html:
    theme: cosmo
    highlight-style: nord
    css: styles.css
    toc: true

editor: visual
