---
title: "Leituras"
subtitle: "Leituras da disciplina introR: introdução à linguagem R."
page-layout: full
title-block-banner: false
toc: true
editor: source
---

## Aula teórica 1: controle de versão

Braga, P. H. P., Hébert, K., Hudgins, E. J., Scott, E. R., Edwards, B. P. M., Sánchez Reyes, L. L., Grainger, M. J., Foroughirad, V., Hillemann, F., Binley, A. D., Brookson, C. B., Gaynor, K. M., Shafiei Sabet, S., Güncan, A., Weierbach, H., Gomes, D. G. E., & Crystal-Ornelas, R. (2023). [Not just for programmers: How GitHub can accelerate collaborative and reproducible research in ecology and evolution](https://doi.org/10.1111/2041-210X.14108). Methods in Ecology and Evolution, 14(6), 1364–1380. 

Chacon, S., Straub, B. (2014). [Pro Git](https://git-scm.com/book/en/v2). 2 ed. Apress.

Perez-Riverol, Y., Gatto, L., Wang, R., Sachsenberg, T., Uszkoreit, J., Leprevost, F. da V., Fufezan, C., Ternent, T., Eglen, S. J., Katz, D. S., Pollard, T. J., Konovalov, A., Flight, R. M., Blin, K., & Vizcaíno, J. A. (2016). [Ten Simple Rules for Taking Advantage of Git and GitHub](https://doi.org/10.1371/journal.pcbi.1004947). PLOS Computational Biology, 12(7), e1004947. 

Kim, A. Y., Herrmann, V., Barreto, R., Calkins, B., Gonzalez-Akre, E., Johnson, D. J., Jordan, J. A., Magee, L., McGregor, I. R., Montero, N., Novak, K., Rogers, T., Shue, J., & Anderson-Teixeira, K. J. (2022). [Implementing GitHub Actions continuous integration to reduce error rates in ecological data collection](https://doi.org/10.1111/2041-210X.13982). Methods in Ecology and Evolution, 13(11), 2572–2585. 

Lowndes, J. S. S., Best, B. D., Scarborough, C., Afflerbach, J. C., Frazier, M. R., O’Hara, C. C., Jiang, N., & Halpern, B. S. (2017). [Our path to better science in less time using open data science tools](https://doi.org/10.1038/s41559-017-0160). Nature Ecology & Evolution, 1(6), 0160.

## Aula teórica 2: introdução à programação em R (Base R)

Da Silva, F. R., Gonçalves-Souza, T., Paterno, G. B., Provete, D. B., & Vancine, M. H. (2022). [Análises Ecológicas no R](https://analises-ecologicas.com/). Recife: Nupeea. Bauru, SP: Canal 6.

Grolemund, G. (2014). [Hands-on programming with R](https://rstudio-education.github.io/hopr). O’Reilly.

Ihaka, R., & Gentleman, R. (1996). [R: A Language for Data Analysis and Graphics](https://doi.org/10.2307/1390807). Journal of Computational and Graphical Statistics, 5(3), 299.

Matloff, N. S. (2011). The art of R programming: Tour of statistical software design. No Starch Press.

## Aula teórica 3: introdução à programação em R (tidyverse)

Wickham, H. (2014). [Tidy data](https://doi.org/10.18637/jss.v059.i10). Journal of Statistical Software 59(10): 1-23.

Wickham, H. et al. (2019). [Welcome to the Tidyverse](https://joss.theoj.org/papers/10.21105/joss.01686). Journal of Open Source Software 4(43): 1686.

Da Silva, F. R., Gonçalves-Souza, T., Paterno, G. B., Provete, D. B., & Vancine, M. H. (2022). [Análises Ecológicas no R](https://analises-ecologicas.com/). Recife: Nupeea. Bauru, SP: Canal 6.

Damiani A, Milz B, Lente C, Falbel D, Correa F, Trecenti J, Luduvice N, Lacerda T, Amorim W. (2025). [Ciência de Dados em R](https://livro.curso-r.com).

Oliveira PF, Guerra S, Mcdonnell, R. (2018). [Ciência de dados com R – Introdução](https://cdr.ibpad.com.br). IBPAD.

Wickham, H., Cetinkaya-Rundel, M., Grolemund, G. (2023.) [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://r4ds.hadley.nz). O'Reilly Media.

## Aula teórica 4: introdução à programação em R (visualização)

Allen, M., Poggiali, D., Whitaker, K., Marshall, T. R., Van Langen, J., & Kievit, R. A. (2021). [Raincloud plots: A multi-platform tool for robust data visualization](https://doi.org/10.12688/wellcomeopenres.15191.2). Wellcome Open Research, 4, 63. 

Butler, R. C. (2022). [Popularity leads to bad habits: Alternatives to “the statistics” routine of significance, “alphabet soup” and dynamite plots](https://doi.org/10.1111/aab.12734). Annals of Applied Biology, 180(2), 182–195. 
Chang W. 2013. [R Graphics Cookbook: Practical Recipes for Visualizing Data](https://r-graphics.org). 2 ed. O'Reilly Media.

Doggett, T. J., & Way, C. (2024). [Dynamite plots in surgical research over 10 years: A meta-study using machine-learning analysis](https://doi.org/10.1093/postmj/qgad134). Postgraduate Medical Journal, 100(1182), 262–266. 

Drummond, G., & Vowler, S. (2011). [Show the data, don’t conceal them](https://doi.org/10.1111/j.1476-5381.2011.01251.x). British Journal of Pharmacology, 163(2), 208–210. 

Emerson, J. W., Green, W. A., Schloerke, B., Crowley, J., Cook, D., Hofmann, H., & Wickham, H. (2013). [The Generalized Pairs Plot](https://doi.org/10.1080/10618600.2012.694762). Journal of Computational and Graphical Statistics, 22(1), 79–91. 

Hickey, G. L., Mokhles, M. M., Chambers, D. J., & Kolamunnage-Dona, R. (2018). [Statistical primer: Performing repeated-measures analysis](https://doi.org/10.1093/icvts/ivy009). Interactive CardioVascular and Thoracic Surgery, 26(4), 539–544. 

Kay, M. (2023). [ggdist: Visualizations of Distributions and Uncertainty in the Grammar of Graphics](https://doi.org/10.1109/TVCG.2023.3327195). IEEE Transactions on Visualization and Computer Graphics, 1–11. 

Magnusson, W. E. (2000). Error Bars: Are They the King’s Clothes? Bulletin of the Ecological Society of America, 81(2), 147–150.

Patil, I. (2021). [Visualizations with statistical details: The “ggstatsplot” approach](https://doi.org/10.21105/joss.03167). Journal of Open Source Software, 6(61), 3167. 

Simply Statistics: Open letter to journal editors: [Dynamite plots must die](https://simplystatistics.org/posts/2019-02-21-dynamite-plots-must-die/). (n.d.). Retrieved October 4, 2025.

Weissgerber, T. L., Milic, N. M., Winham, S. J., & Garovic, V. D. (2015). [Beyond Bar and Line Graphs: Time for a New Data Presentation Paradigm](https://doi.org/10.1371/journal.pbio.1002128). PLOS Biology, 13(4), e1002128. 

Wickham H. (2020). [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org). 3 ed. Springer.

Wilk CO. 2019. [Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures](https://serialmentor.com/dataviz). O'Reilly Media.

## Aula teórica 5: tópicos avançados em programação em R

Gagolewski, M. (2024). [Deep R Programming](https://deepr.gagolewski.com/index.html). Marek Gagolewski.

Jones, E., Harden, S., & Crawley, M. J. (2022). The R book. 3 ed. Wiley.

Wickham, H., & Bryan J. (2015). [R packages](https://r-pkgs.org). 2 ed. O’Reilly Media.

Wickham, H. (2019). [Advanced R](https://adv-r.hadley.nz). 2 ed. Chapman and Hall/CRC.

## Aula teórica 6: reprodutibilidade em R e GitHub

Blischak, J. D., Carbonetto, P., & Stephens, M. (2019). [Creating and sharing reproducible research code the workflowr way](https://doi.org/10.12688/f1000research.20843.1). F1000Research.

Buckley, Y. M., Bardgett, R., Gordon, R., Iler, A., Mariotte, P., Ponton, S., & Hector, A. (2025). [Using dynamic documents to mend cracks in the reproducible research pipeline](https://doi.org/10.1111/1365-2745.14454). Journal of Ecology, 113(2), 270–274.

Chen, K. Y., Toro-Moreno, M., & Subramaniam, A. R. (2025). [GitHub is an effective platform for collaborative and reproducible laboratory research](https://arxiv.org/abs/2408.09344). ArXiv, arXiv:2408.09344v2.

Granjon, D. (2022). [Outstanding user interfaces with Shiny](https://doi.org/10.1201/9781003124924). CRC Press.

Kamvar, Z. N., López-Uribe, M. M., Coughlan, S., Grünwald, N. J., Lapp, H., & Manel, S. (2017). [Developing educational resources for population genetics in R: An open and collaborative approach](https://doi.org/10.1111/1755-0998.12558). Molecular Ecology Resources, 17(1), 120–128. 

Peikert, A., & Brandmaier, A. M. (2021). [A Reproducible Data Analysis Workflow With R Markdown, Git, Make, and Docker](https://doi.org/10.5964/qcmb.3763). Quantitative and Computational Methods in Behavioral Sciences, 1–27.

Peikert, A., van Lissa, C. J., & Brandmaier, A. M. (2021). [Reproducible Research in R: A Tutorial on How to Do the Same Thing More Than Once](https://doi.org/10.3390/psych3040053). Psych, 3(4), 836–867.

Sievert, C. (2020). Interactive web-based data visualization with R, plotly, and shiny. CRC Press, Taylor and Francis Group.

Weberpals, J., & Wang, S. V. (2024). [The FAIRification of research in real-world evidence: A practical introduction to reproducible analytic workflows using Git and R](https://doi.org/10.1002/pds.5740). Pharmacoepidemiology and Drug Safety, 33(1), e5740.

Wickham, H. (2021). [Mastering Shiny: Build Interactive Apps, Reports, and Dashboards Powered by R](https://mastering-shiny.org/). O’Reilly Media. 

## Discussão: ciência aberta e reprodutibilidade

Alston, J. M., & Rick, J. A. (2021). [A Beginner's Guide to Conducting Reproducible Research](https://doi.org/10.1002/bes2.1801). Bulletin of the Ecological Society of America, 102(2), 1–14.

BES, & Cooper, N. (2017). [A Guide to Reproducible Code in Ecology and Evolution](https://nhm.openrepository.com/handle/10141/622618).

Borregaard, M. K., & Hart, E. M. (2016). [Towards a more reproducible ecology](https://doi.org/10.1111/ecog.02493). Ecography, 39(4), 349–353. 

Casadevall, A., & Fang, F. C. (2010). [Reproducible Science](https://doi.org/10.1128/IAI.00908-10). Infection and Immunity, 78(12), 4972–4975. 

Cassey, P., & Blackburn, T. M. (2006). [Reproducibility and Repeatability in Ecology](https://doi.org/10.1641/0006-3568(2006)56[958:RARIE]2.0.CO;2). BioScience, 56(12), 958–959. 

Fidler, F., Chee, Y. E., Wintle, B. C., Burgman, M. A., McCarthy, M. A., & Gordon, A. (2017). [Metaresearch for Evaluating Reproducibility in Ecology and Evolution](https://doi.org/10.1093/biosci/biw159). BioScience, biw159. 

Goodman, S. N., Fanelli, D., & Ioannidis, J. P. A. (2016). [What does research reproducibility mean?](https://doi.org/10.1126/scitranslmed.aaf5027) Science Translational Medicine, 8(341), 341ps12-341ps12. 

Hurley, A. G., Peters, R. L., Pappas, C., Steger, D. N., & Heinrich, I. (2022). [Addressing the need for interactive, efficient, and reproducible data processing in ecology with the datacleanr R package](https://doi.org/10.1371/journal.pone.0268426). PLOS ONE, 17(5), e0268426.

Jenkins, G. B., Beckerman, A. P., Bellard, C., Benítez‐López, A., Ellison, A. M., Foote, C. G., Hufton, A. L., Lashley, M. A., Lortie, C. J., Ma, Z., Moore, A. J., Narum, S. R., Nilsson, J., O’Boyle, B., Provete, D. B., Razgour, O., Rieseberg, L., Riginos, C., Santini, L., … Peres‐Neto, P. R. (2023). [Reproducibility in ecology and evolution: Minimum standards for data and code](https://doi.org/10.1002/ece3.9961). Ecology and Evolution, 13(5), e9961. 

Munafò, M. R., Nosek, B. A., Bishop, D. V. M., Button, K. S., Chambers, C. D., Percie du Sert, N., Simonsohn, U., Wagenmakers, E.-J., Ware, J. J., & Ioannidis, J. P. A. (2017). [A manifesto for reproducible science](https://doi.org/10.1038/s41562-016-0021). Nature Human Behaviour, 1(1), Article 1. 

Peng, R. D. (2011). [Reproducible Research in Computational Science](https://doi.org/10.1126/science.1213847). Science, 334(6060), 1226–1227. 

Sánchez-Tójar, A., Bezine, A., Purgar, M., & Culina, A. (2025). [Code-sharing policies are associated with increased reproducibility potential of ecological findings](https://doi.org/10.24072/pcjournal.541). Peer Community Journal, 5. 

Wilkinson, M. D., Dumontier, M., Aalbersberg, Ij. J., Appleton, G., Axton, M., Baak, A., Blomberg, N., Boiten, J.-W., Da Silva Santos, L. B., Bourne, P. E., Bouwman, J., Brookes, A. J., Clark, T., Crosas, M., Dillo, I., Dumon, O., Edmunds, S., Evelo, C. T., Finkers, R., … Mons, B. (2016). [The FAIR Guiding Principles for scientific data management and stewardship](https://doi.org/10.1038/sdata.2016.18). Scientific Data, 3(1), 160018. 

Wilson, G., Bryan, J., Cranston, K., Kitzes, J., Nederbragt, L., & Teal, T. K. (2017). [Good enough practices in scientific computing](https://doi.org/10.1371/journal.pcbi.1005510). PLOS Computational Biology, 13(6), e1005510.

## Tópico especial I: Ciência Aberta (*Open Science*)

Barnes, N. (2010). [Publish your computer code: It is good enough](https://doi.org/10.1038/467753a). Nature, 467(7317), Article 7317.

Hampton, S. E., Anderson, S. S., Bagby, S. C., Gries, C., Han, X., Hart, E. M., Jones, M. B., Lenhardt, W. C., MacDonald, A., Michener, W. K., Mudge, J., Pourmokhtarian, A., Schildhauer, M. P., Woo, K. H., & Zimmerman, N. (2015). [The Tao of open science for ecology](https://doi.org/10.1890/ES14-00402.1). Ecosphere, 6(7), art120.

Lortie, C. J. (2017). [Open Sesame: R for Data Science is Open Science](https://ojs.library.queensu.ca/index.php/IEE/article/view/6559). Ideas in Ecology and Evolution, 10(1), Article 1. 

Lowndes, J. S. S., Best, B. D., Scarborough, C., Afflerbach, J. C., Frazier, M. R., O’Hara, C. C., Jiang, N., & Halpern, B. S. (2017). [Our path to better science in less time using open data science tools](https://doi.org/10.1038/s41559-017-0160). Nature Ecology & Evolution, 1(6), 0160. 

Maedche, A., Elshan, E., Höhle, H., Lehrer, C., Recker, J., Sunyaev, A., Sturm, B., & Werth, O. (2024). [Open Science](https://doi.org/10.1007/s12599-024-00858-7). Business & Information Systems Engineering, 66(4), 517–532.

Mendes-Da-Silva, W. (2023). [O que cocentes e pesquisadores na área de gestão de negócios precisam saber a respeito de ciência aberta]( https://doi.org/10.1590/S0034-759020230408). Revista de Administração de Empresas, 63, e0000.

Mislan, K. A. S., Heer, J. M., & White, E. P. (2016). [Elevating The Status of Code in Ecology](https://doi.org/10.1016/j.tree.2015.11.006). Trends in Ecology & Evolution, 31(1), 4–7. 

Nosek, B. A., Alter, G., Banks, G. C., Borsboom, D., Bowman, S. D., Breckler, S. J., Buck, S., Chambers, C. D., Chin, G., Christensen, G., Contestabile, M., Dafoe, A., Eich, E., Freese, J., Glennerster, R., Goroff, D., Green, D. P., Hesse, B., Humphreys, M., … Yarkoni, T. (2015). [Promoting an open research culture](https://doi.org/10.1126/science.aab2374). Science, 348(6242), 1422–1425.

Ramachandran, R., Bugbee, K., & Murphy, K. (2021). [From Open Data to Open Science](https://doi.org/10.1029/2020EA001562). Earth and Space Science, 8(5), e2020EA001562. 

Roche, D. G., Kruuk, L. E. B., Lanfear, R., & Binning, S. A. (2015). [Public Data Archiving in Ecology and Evolution: How Well Are We Doing?](https://doi.org/10.1371/journal.pbio.1002295) PLOS Biology, 13(11), e1002295.

Thibault, R. T., Amaral, O. B., Argolo, F., Bandrowski, A. E., Alexandra R, D., & Drude, N. I. (2023). [Open Science 2.0: Towards a truly collaborative research ecosystem](https://doi.org/10.1371/journal.pbio.3002362). PLOS Biology, 21(10), e3002362. 

## Tópico especial II: Large Language Models (LLMs)

Binz, M., Alaniz, S., Roskies, A., Aczel, B., Bergstrom, C. T., Allen, C., Schad, D., Wulff, D., West, J. D., Zhang, Q., Shiffrin, R. M., Gershman, S. J., Popov, V., Bender, E. M., Marelli, M., Botvinick, M. M., Akata, Z., & Schulz, E. (2025). [How should the advancement of large language models affect the practice of science?](https://doi.org/10.1073/pnas.2401227121) Proceedings of the National Academy of Sciences, 122(5), e2401227121.

Brown, C. J., & Spillias, S. (2025). [Prompting large language models for quality ecological statistics](https://ecoevorxiv.org/repository/view/9493/). EcoEvoRxiv. 

Campbell, H., Bluck, T., Curry, E., Harris, D., Pike, B., & Wright, B. (2024).[Should we still teach or learn coding? A postgraduate student perspective on the use of large language models for coding in ecology and evolution](https://doi.org/10.1111/2041-210X.14396). Methods in Ecology and Evolution, 15(10), 1767–1770. 

Castro, A., Pinto, J., Reino, L., Pipek, P., & Capinha, C. (2024). [Large language models overcome the challenges of unstructured text data in ecology](https://doi.org/10.1016/j.ecoinf.2024.102742). Ecological Informatics, 82, 102742. 

Cooper, N., Clark, A. T., Lecomte, N., Qiao, H., & Ellison, A. M. (2024). [Harnessing large language models for coding, teaching and inclusion to empower research in ecology and evolution](https://doi.org/10.1111/2041-210X.14325). Methods in Ecology and Evolution, 15(10), 1757–1763.

Dorm, F., Millard, J., Purves, D., Harfoot, M., & Aodha, O. M. (2025). [Large language models possess some ecological knowledge, but how much?](https://doi.org/10.1101/2025.02.10.637097) (p. 2025.02.10.637097). bioRxiv.

Johnson, T. F., Simmons, B. I., Millard, J., Strydom, T., Danet, A., Sweeny, A. R., & Evans, L. C. (2024). [Pressure to publish introduces large-language model risks](https://doi.org/10.1111/2041-210X.14397). Methods in Ecology and Evolution, 15(10), 1771–1773.

Mammides, C., & Papadopoulos, H. (2024). [The role of large language models in interdisciplinary research: Opportunities, challenges and ways forward](https://doi.org/10.1111/2041-210X.14398). Methods in Ecology and Evolution, 15(10), 1774–1776.

Millard, J., Christie, A. P., Dicks, L. V., Isip, J. E., Johnson, T. F., Skinner, G., & Spake, R. (2024). [ChatGPT is likely reducing opportunity for support, friendship and learned kindness in research](https://doi.org/10.1111/2041-210X.14395). Methods in Ecology and Evolution, 15(10), 1764–1766.

Peters, U., & Chin-Yee, B. (2025). [Generalization bias in large language model summarization of scientific research](https://doi.org/10.1098/rsos.241776). Royal Society Open Science, 12(4), 241776.

Smith, G. R., Bello, C., Bialic-Murphy, L., Clark, E., Delavaux, C. S., Lauriere, C. F. de, Hoogen, J. van den, Lauber, T., Ma, H., Maynard, D. S., Mirman, M., Mo, L., Rebindaine, D., Reek, J. E., Werden, L. K., Wu, Z., Yang, G., Zhao, Q., Zohner, C. M., & Crowther, T. W. (2024). [Ten simple rules for using large language models in science, version 1.0](https://doi.org/10.1371/journal.pcbi.1011767). PLOS Computational Biology, 20(1), e1011767. 

[The rise of large language models](https://doi.org/10.1038/s43588-025-00890-x). (2025). Nature Computational Science, 5(9), 689–690.

Wills, S., Poon, S. T. S., Salili-James, A., & Scott, B. (2024).[ The use of generative AI for coding in academia](https://doi.org/10.1111/2041-210X.14454). Methods in Ecology and Evolution, 15(12), 2189–2191.

Yu, S., Ran, N., & Liu, J. (2024). [Large-language models: The game-changers for materials science research](https://doi.org/10.1016/j.aichem.2024.100076). Artificial Intelligence Chemistry, 2(2), 100076. 

Zhang, Q., Ding, K., Lv, T., Wang, X., Yin, Q., Zhang, Y., Yu, J., Wang, Y., Li, X., Xiang, Z., Zhuang, X., Wang, Z., Qin, M., Zhang, M., Zhang, J., Cui, J., Xu, R., Chen, H., Fan, X., … Chen, H. (2025). [Scientific Large Language Models: A Survey on Biological & Chemical Domains](https://doi.org/10.1145/3715318). ACM Comput. Surv., 57(6), 161:1-161:38. 

Zhang, Y., Khan, S. A., Mahmud, A., Yang, H., Lavin, A., Levin, M., Frey, J., Dunnmon, J., Evans, J., Bundy, A., Dzeroski, S., Tegner, J., & Zenil, H. (2025). [Exploring the role of large language models in the scientific method: From hypothesis to discovery](https://doi.org/10.1038/s44387-025-00019-5). Npj Artificial Intelligence, 1(1), 14. 
Zhang, Y., Lin, S., Xiong, Y., Li, N., Zhong, L., Ding, L., & Hu, Q. (2025). [Fine-tuning large language models for interdisciplinary environmental challenges](https://doi.org/10.1016/j.ese.2025.100608). Environmental Science and Ecotechnology, 27, 100608. 

<style>
#topBtn {
  display: none;
  position: fixed;
  bottom: 105px; /* um pouco acima do fundo */
  left: 50%;
  transform: translateX(-50%);
  padding: 10px 14px;
  font-size: 20px;
  border: none;
  border-radius: 6px;
  background-color: #2381df; 
  color: white;
  cursor: pointer;
  box-shadow: 0 2px 6px rgba(0,0,0,0.3);
  transition: background-color 0.3s;
}
#topBtn:hover {
  background-color: rgba(0, 86, 179, 0.9);
}
</style>

<button id="topBtn" onclick="window.scrollTo({top: 0, behavior: 'smooth'});">↑ Topo</button>

<script>
const btn = document.getElementById("topBtn");

window.addEventListener("scroll", () => {
  const scrollBottom = window.innerHeight + window.scrollY;
  const docHeight = document.documentElement.scrollHeight;

  if (scrollBottom >= docHeight - 200) { // aparece um pouco antes do final
    btn.style.display = "block";
  } else {
    btn.style.display = "none";
  }
});
</script>
